---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: linux-polska-blog
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: linux-polska-blog
    spec:
      containers:
      - name: linux-polska-blog
        image: buker/jekyll:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: linux-polska-blog
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: linux-polska-blog
